<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <RootNamespace>QuestPDF.FSharp</RootNamespace>
        <AssemblyName>QuestPDF.FSharp</AssemblyName>
        <PackageId>QuestPDF.FSharp</PackageId>
        <Title>QuestPDF.FSharp</Title>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Library.fs" />
        <None Include="../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
