<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <RootNamespace>QuestPDF.FSharp</RootNamespace>
        <AssemblyName>QuestPDF.FSharp</AssemblyName>
        <PackageId>QuestPDF.FSharp</PackageId>
        <Title>QuestPDF.FSharp</Title>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Units.fs" />
        <Compile Include="Primitives.fs" />
        <Compile Include="Core.fs" />
        <Compile Include="Measured.fs" />
        <Compile Include="Style.fs" />
        <Compile Include="Modifiers.fs" />
        <Compile Include="Text.fs" />
        <Compile Include="Layout.fs" />
        <Compile Include="Document.fs" />
        <Compile Include="Generate.fs" />
        <Compile Include="Setup.fs" />
        <None Include="../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="QuestPDF" Version="2026.9.0" />
    </ItemGroup>

</Project>
