<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Invoice.fs" />
        <Compile Include="Program.fs" />
        <None Include="preview.fsx" />
        <None Include="invoice.fsx" />
        <None Include="parts/header.fsx" />
        <None Include="README.md" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\FSharp.QuestPDF\FSharp.QuestPDF.fsproj" />
        <ProjectReference Include="..\..\src\FSharp.QuestPDF.Preview\FSharp.QuestPDF.Preview.fsproj" />
    </ItemGroup>

</Project>
